# Generated by Django 4.2.8 on 2024-01-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.CharField(default=10, max_length=20, null=True),
        ),
    ]
