# Generated by Django 4.2.8 on 2024-01-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_peminjaman_loginhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
